# Notebook: 03_gold_kpis_comerciais
# Objetivo: criar marts e KPIs Gold para consumo direto em Power BI.
# Premissa: executar previamente 00_config_gold.py, 01_gold_dimensoes_conformadas.py e 02_gold_fatos_modeladas.py.

spark.sql(f"CREATE DATABASE IF NOT EXISTS {GOLD_SCHEMA}")

# KPI mensal de vendas por loja, canal e categoria
spark.sql(f"""
CREATE OR REPLACE TABLE {GOLD_TABLES['kpi_vendas_mensal']} AS
SELECT
    t.ANO,
    t.MES,
    t.ANO_MES,
    v.SK_LOJA,
    l.NOME_LOJA,
    l.REGIONAL,
    l.ESTADO,
    v.SK_CANALVENDA,
    cv.NOME_CANALVENDA,
    v.SK_CATEGORIA,
    p.NOME_CATEGORIA,
    SUM(v.VALOR_BRUTO) AS FATURAMENTO_BRUTO,
    SUM(v.VALOR_DESCONTO) AS VALOR_DESCONTO,
    SUM(v.VALOR_LIQUIDO) AS FATURAMENTO_LIQUIDO,
    SUM(v.CUSTO_TOTAL) AS CUSTO_TOTAL,
    SUM(v.MARGEM_BRUTA) AS MARGEM_BRUTA,
    CASE WHEN SUM(v.VALOR_LIQUIDO) > 0 THEN ROUND(SUM(v.MARGEM_BRUTA) / SUM(v.VALOR_LIQUIDO) * 100, 4) ELSE NULL END AS PERCENTUAL_MARGEM,
    SUM(v.QUANTIDADE) AS QTD_ITENS,
    COUNT(DISTINCT v.ID_VENDA_ORIGEM) AS QTD_VENDAS,
    COUNT(DISTINCT v.SK_CLIENTE) AS QTD_CLIENTES,
    CASE WHEN COUNT(DISTINCT v.ID_VENDA_ORIGEM) > 0 THEN ROUND(SUM(v.VALOR_LIQUIDO) / COUNT(DISTINCT v.ID_VENDA_ORIGEM), 2) ELSE NULL END AS TICKET_MEDIO,
    current_timestamp() AS gold_data_processamento
FROM {GOLD_TABLES['fato_vendas']} v
LEFT JOIN {GOLD_TABLES['dim_tempo']} t ON v.SK_TEMPO = t.SK_TEMPO
LEFT JOIN {GOLD_TABLES['dim_loja']} l ON v.SK_LOJA = l.SK_LOJA
LEFT JOIN {GOLD_TABLES['dim_canal_venda']} cv ON v.SK_CANALVENDA = cv.SK_CANALVENDA
LEFT JOIN {GOLD_TABLES['dim_produto']} p ON v.SK_PRODUTO = p.SK_PRODUTO
GROUP BY
    t.ANO,
    t.MES,
    t.ANO_MES,
    v.SK_LOJA,
    l.NOME_LOJA,
    l.REGIONAL,
    l.ESTADO,
    v.SK_CANALVENDA,
    cv.NOME_CANALVENDA,
    v.SK_CATEGORIA,
    p.NOME_CATEGORIA
""")

# Meta versus realizado no mesmo grao das metas: mes, loja, canal e categoria
spark.sql(f"""
CREATE OR REPLACE TABLE {GOLD_TABLES['kpi_meta_vs_realizado']} AS
WITH realizado AS (
    SELECT
        t.ANO_MES,
        v.SK_LOJA,
        v.SK_CANALVENDA,
        v.SK_CATEGORIA,
        SUM(v.VALOR_BRUTO) AS FATURAMENTO_BRUTO_REALIZADO,
        SUM(v.VALOR_LIQUIDO) AS FATURAMENTO_LIQUIDO_REALIZADO,
        SUM(v.MARGEM_BRUTA) AS MARGEM_BRUTA_REALIZADA,
        SUM(v.QUANTIDADE) AS QTD_ITENS_REALIZADA,
        COUNT(DISTINCT v.ID_VENDA_ORIGEM) AS QTD_VENDAS_REALIZADA
    FROM {GOLD_TABLES['fato_vendas']} v
    LEFT JOIN {GOLD_TABLES['dim_tempo']} t ON v.SK_TEMPO = t.SK_TEMPO
    GROUP BY
        t.ANO_MES,
        v.SK_LOJA,
        v.SK_CANALVENDA,
        v.SK_CATEGORIA
)
SELECT
    m.ANO,
    m.MES,
    m.ANO_MES,
    m.SK_LOJA,
    l.NOME_LOJA,
    l.REGIONAL,
    m.SK_CANALVENDA,
    cv.NOME_CANALVENDA,
    m.SK_CATEGORIA,
    p.NOME_CATEGORIA,
    m.TIPO_META,
    m.META_FATURAMENTO_BRUTO,
    m.META_FATURAMENTO_LIQUIDO,
    m.META_QTD_VENDAS,
    m.META_QTD_ITENS,
    m.META_TICKET_MEDIO,
    m.META_MARGEM_BRUTA,
    m.META_PERCENTUAL_MARGEM,
    COALESCE(r.FATURAMENTO_BRUTO_REALIZADO, 0) AS FATURAMENTO_BRUTO_REALIZADO,
    COALESCE(r.FATURAMENTO_LIQUIDO_REALIZADO, 0) AS FATURAMENTO_LIQUIDO_REALIZADO,
    COALESCE(r.MARGEM_BRUTA_REALIZADA, 0) AS MARGEM_BRUTA_REALIZADA,
    COALESCE(r.QTD_ITENS_REALIZADA, 0) AS QTD_ITENS_REALIZADA,
    COALESCE(r.QTD_VENDAS_REALIZADA, 0) AS QTD_VENDAS_REALIZADA,
    COALESCE(r.FATURAMENTO_LIQUIDO_REALIZADO, 0) - m.META_FATURAMENTO_LIQUIDO AS DESVIO_META_VALOR,
    CASE WHEN m.META_FATURAMENTO_LIQUIDO > 0 THEN ROUND(COALESCE(r.FATURAMENTO_LIQUIDO_REALIZADO, 0) / m.META_FATURAMENTO_LIQUIDO * 100, 4) ELSE NULL END AS PERCENTUAL_ATINGIMENTO_META,
    CASE
        WHEN m.META_FATURAMENTO_LIQUIDO = 0 THEN 'SEM_META'
        WHEN COALESCE(r.FATURAMENTO_LIQUIDO_REALIZADO, 0) / m.META_FATURAMENTO_LIQUIDO >= 1 THEN 'ACIMA_DA_META'
        WHEN COALESCE(r.FATURAMENTO_LIQUIDO_REALIZADO, 0) / m.META_FATURAMENTO_LIQUIDO >= 0.9 THEN 'PROXIMO_DA_META'
        ELSE 'ABAIXO_DA_META'
    END AS STATUS_META,
    current_timestamp() AS gold_data_processamento
FROM {GOLD_TABLES['fato_metas']} m
LEFT JOIN realizado r
    ON m.ANO_MES = r.ANO_MES
   AND m.SK_LOJA = r.SK_LOJA
   AND m.SK_CANALVENDA = r.SK_CANALVENDA
   AND m.SK_CATEGORIA = r.SK_CATEGORIA
LEFT JOIN {GOLD_TABLES['dim_loja']} l ON m.SK_LOJA = l.SK_LOJA
LEFT JOIN {GOLD_TABLES['dim_canal_venda']} cv ON m.SK_CANALVENDA = cv.SK_CANALVENDA
LEFT JOIN {GOLD_TABLES['dim_produto']} p ON m.SK_CATEGORIA = p.SK_CATEGORIA
""")

# KPI de estoque atual: ultima data disponivel por produto e loja
spark.sql(f"""
CREATE OR REPLACE TABLE {GOLD_TABLES['kpi_estoque_atual']} AS
WITH ultima_data AS (
    SELECT MAX(SK_TEMPO) AS SK_TEMPO_MAX
    FROM {GOLD_TABLES['fato_estoque']}
)
SELECT
    e.SK_TEMPO,
    t.DATA_COMPLETA AS DATA_REFERENCIA,
    e.SK_LOJA,
    l.NOME_LOJA,
    l.REGIONAL,
    e.SK_PRODUTO,
    p.NOME_PRODUTO,
    p.NOME_CATEGORIA,
    p.NOME_MARCA,
    p.NOME_FORNECEDOR,
    e.QTD_ESTOQUE_DISPONIVEL,
    e.QTD_ESTOQUE_TOTAL,
    e.QTD_ESTOQUE_MINIMO,
    e.QTD_ESTOQUE_MAXIMO,
    e.QTD_PONTO_REPOSICAO,
    e.VALOR_ESTOQUE_CUSTO,
    e.VALOR_ESTOQUE_VENDA,
    e.DIAS_COBERTURA_ESTOQUE,
    e.GIRO_ESTOQUE,
    e.IND_RUPTURA,
    e.IND_ESTOQUE_BAIXO,
    e.IND_EXCESSO_ESTOQUE,
    CASE
        WHEN e.IND_RUPTURA = 1 THEN 'RUPTURA'
        WHEN e.IND_ESTOQUE_BAIXO = 1 THEN 'ESTOQUE_BAIXO'
        WHEN e.IND_EXCESSO_ESTOQUE = 1 THEN 'EXCESSO'
        ELSE 'NORMAL'
    END AS STATUS_ESTOQUE,
    current_timestamp() AS gold_data_processamento
FROM {GOLD_TABLES['fato_estoque']} e
JOIN ultima_data u ON e.SK_TEMPO = u.SK_TEMPO_MAX
LEFT JOIN {GOLD_TABLES['dim_tempo']} t ON e.SK_TEMPO = t.SK_TEMPO
LEFT JOIN {GOLD_TABLES['dim_loja']} l ON e.SK_LOJA = l.SK_LOJA
LEFT JOIN {GOLD_TABLES['dim_produto']} p ON e.SK_PRODUTO = p.SK_PRODUTO
""")

# KPI mensal de ruptura por loja, categoria e motivo
spark.sql(f"""
CREATE OR REPLACE TABLE {GOLD_TABLES['kpi_ruptura_mensal']} AS
SELECT
    t.ANO,
    t.MES,
    t.ANO_MES,
    r.SK_LOJA,
    l.NOME_LOJA,
    l.REGIONAL,
    p.SK_CATEGORIA,
    p.NOME_CATEGORIA,
    r.SK_MOTIVO_RUPTURA,
    mr.DESCRICAO_RUPTURA,
    mr.TIPO_RUPTURA,
    COUNT(DISTINCT r.ID_RUPTURA_ORIGEM) AS QTD_EVENTOS_RUPTURA,
    SUM(r.QTD_RUPTURA) AS QTD_TOTAL_RUPTURA,
    SUM(r.DIAS_RUPTURA) AS DIAS_RUPTURA_TOTAL,
    SUM(r.VALOR_VENDA_PERDIDA) AS VALOR_VENDA_PERDIDA,
    current_timestamp() AS gold_data_processamento
FROM {GOLD_TABLES['fato_ruptura_estoque']} r
LEFT JOIN {GOLD_TABLES['dim_tempo']} t ON r.SK_TEMPO = t.SK_TEMPO
LEFT JOIN {GOLD_TABLES['dim_loja']} l ON r.SK_LOJA = l.SK_LOJA
LEFT JOIN {GOLD_TABLES['dim_produto']} p ON r.SK_PRODUTO = p.SK_PRODUTO
LEFT JOIN {GOLD_TABLES['dim_motivo_ruptura']} mr ON r.SK_MOTIVO_RUPTURA = mr.SK_MOTIVO_RUPTURA
GROUP BY
    t.ANO,
    t.MES,
    t.ANO_MES,
    r.SK_LOJA,
    l.NOME_LOJA,
    l.REGIONAL,
    p.SK_CATEGORIA,
    p.NOME_CATEGORIA,
    r.SK_MOTIVO_RUPTURA,
    mr.DESCRICAO_RUPTURA,
    mr.TIPO_RUPTURA
""")

print("KPIs e marts Gold criados com sucesso.")
