# Notebook: 04_gold_mart_resumo_executivo
# Objetivo: criar uma tabela consolidada de indicadores executivos para BI.
# Premissa: executar previamente 03_gold_kpis_comerciais.py.

spark.sql(f"CREATE DATABASE IF NOT EXISTS {GOLD_SCHEMA}")

spark.sql(f"""
CREATE OR REPLACE TABLE {GOLD_TABLES['mart_resumo_executivo']} AS
WITH vendas AS (
    SELECT
        ANO_MES,
        SUM(FATURAMENTO_LIQUIDO) AS FATURAMENTO_LIQUIDO,
        SUM(MARGEM_BRUTA) AS MARGEM_BRUTA,
        SUM(QTD_VENDAS) AS QTD_VENDAS,
        SUM(QTD_ITENS) AS QTD_ITENS,
        CASE WHEN SUM(QTD_VENDAS) > 0 THEN ROUND(SUM(FATURAMENTO_LIQUIDO) / SUM(QTD_VENDAS), 2) ELSE NULL END AS TICKET_MEDIO
    FROM {GOLD_TABLES['kpi_vendas_mensal']}
    GROUP BY ANO_MES
),
metas AS (
    SELECT
        ANO_MES,
        SUM(META_FATURAMENTO_LIQUIDO) AS META_FATURAMENTO_LIQUIDO,
        SUM(FATURAMENTO_LIQUIDO_REALIZADO) AS FATURAMENTO_REALIZADO_META,
        CASE WHEN SUM(META_FATURAMENTO_LIQUIDO) > 0 THEN ROUND(SUM(FATURAMENTO_LIQUIDO_REALIZADO) / SUM(META_FATURAMENTO_LIQUIDO) * 100, 4) ELSE NULL END AS PERCENTUAL_ATINGIMENTO_META
    FROM {GOLD_TABLES['kpi_meta_vs_realizado']}
    GROUP BY ANO_MES
),
ruptura AS (
    SELECT
        ANO_MES,
        SUM(QTD_EVENTOS_RUPTURA) AS QTD_EVENTOS_RUPTURA,
        SUM(VALOR_VENDA_PERDIDA) AS VALOR_VENDA_PERDIDA
    FROM {GOLD_TABLES['kpi_ruptura_mensal']}
    GROUP BY ANO_MES
)
SELECT
    v.ANO_MES,
    v.FATURAMENTO_LIQUIDO,
    v.MARGEM_BRUTA,
    CASE WHEN v.FATURAMENTO_LIQUIDO > 0 THEN ROUND(v.MARGEM_BRUTA / v.FATURAMENTO_LIQUIDO * 100, 4) ELSE NULL END AS PERCENTUAL_MARGEM,
    v.QTD_VENDAS,
    v.QTD_ITENS,
    v.TICKET_MEDIO,
    m.META_FATURAMENTO_LIQUIDO,
    m.PERCENTUAL_ATINGIMENTO_META,
    COALESCE(r.QTD_EVENTOS_RUPTURA, 0) AS QTD_EVENTOS_RUPTURA,
    COALESCE(r.VALOR_VENDA_PERDIDA, 0) AS VALOR_VENDA_PERDIDA,
    current_timestamp() AS gold_data_processamento
FROM vendas v
LEFT JOIN metas m ON v.ANO_MES = m.ANO_MES
LEFT JOIN ruptura r ON v.ANO_MES = r.ANO_MES
""")

print("Mart resumo executivo criado com sucesso.")
