/* ============================================================
   ÍNDICES - dw.FATO_VENDAS
   Objetivo:
   Melhorar performance em consultas analíticas envolvendo tempo,
   cliente, produto, loja, promoção, forma de pagamento, canal,
   categoria, marca e fornecedor.
   ============================================================ */

CREATE INDEX IDX_FV_TEMPO 
ON dw.FATO_VENDAS (SK_TEMPO);

CREATE INDEX IDX_FV_CLIENTE 
ON dw.FATO_VENDAS (SK_CLIENTE);

CREATE INDEX IDX_FV_PRODUTO 
ON dw.FATO_VENDAS (SK_PRODUTO);

CREATE INDEX IDX_FV_LOJA 
ON dw.FATO_VENDAS (SK_LOJA);

CREATE INDEX IDX_FV_PROMOCAO 
ON dw.FATO_VENDAS (SK_PROMOCAO);

CREATE INDEX IDX_FV_FORMAPAGTO 
ON dw.FATO_VENDAS (SK_FORMAPAGTO);

CREATE INDEX IDX_FV_CANALVENDA 
ON dw.FATO_VENDAS (SK_CANALVENDA);

CREATE INDEX IDX_FV_ID_ORIGEM 
ON dw.FATO_VENDAS (ID_VENDA_ORIGEM);

CREATE INDEX IDX_FV_CATEGORIA 
ON dw.FATO_VENDAS (SK_CATEGORIA);

CREATE INDEX IDX_FV_MARCA 
ON dw.FATO_VENDAS (SK_MARCA);

CREATE INDEX IDX_FV_FORNECEDOR 
ON dw.FATO_VENDAS (SK_FORNECEDOR);

CREATE INDEX IDX_FV_DATA_HORA_VENDA 
ON dw.FATO_VENDAS (DATA_HORA_VENDA);

CREATE INDEX IDX_FV_PRODUTO_LOJA_TEMPO 
ON dw.FATO_VENDAS (SK_PRODUTO, SK_LOJA, SK_TEMPO);

CREATE INDEX IDX_FV_LOJA_CANAL_TEMPO 
ON dw.FATO_VENDAS (SK_LOJA, SK_CANALVENDA, SK_TEMPO);

CREATE INDEX IDX_FV_CATEG_MARCA_TEMPO 
ON dw.FATO_VENDAS (SK_CATEGORIA, SK_MARCA, SK_TEMPO);

/* ============================================================
   ÍNDICES - dw.FATO_RUPTURA_ESTOQUE
   Objetivo:
   Melhorar consultas sobre ruptura por período, produto, loja
   e motivo da ruptura.
   ============================================================ */

CREATE INDEX IDX_FR_TEMPO 
ON dw.FATO_RUPTURA_ESTOQUE (SK_TEMPO);

CREATE INDEX IDX_FR_PRODUTO 
ON dw.FATO_RUPTURA_ESTOQUE (SK_PRODUTO);

CREATE INDEX IDX_FR_LOJA 
ON dw.FATO_RUPTURA_ESTOQUE (SK_LOJA);

CREATE INDEX IDX_FR_MOTIVO 
ON dw.FATO_RUPTURA_ESTOQUE (SK_MOTIVO_RUPTURA);

CREATE INDEX IDX_FR_PRODUTO_LOJA_TEMPO 
ON dw.FATO_RUPTURA_ESTOQUE (SK_PRODUTO, SK_LOJA, SK_TEMPO);

CREATE INDEX IDX_FR_LOJA_TEMPO 
ON dw.FATO_RUPTURA_ESTOQUE (SK_LOJA, SK_TEMPO);

CREATE INDEX IDX_FR_FL_RUPTURA 
ON dw.FATO_RUPTURA_ESTOQUE (FL_RUPTURA);

/* ============================================================
   ÍNDICES - dw.FATO_ESTOQUE
   Objetivo:
   Melhorar consultas de posição de estoque por data, produto,
   loja, categoria, marca e fornecedor.
   ============================================================ */

CREATE INDEX IDX_FE_TEMPO
ON dw.FATO_ESTOQUE (SK_TEMPO);

CREATE INDEX IDX_FE_PRODUTO
ON dw.FATO_ESTOQUE (SK_PRODUTO);

CREATE INDEX IDX_FE_LOJA
ON dw.FATO_ESTOQUE (SK_LOJA);

CREATE INDEX IDX_FE_CATEGORIA
ON dw.FATO_ESTOQUE (SK_CATEGORIA);

CREATE INDEX IDX_FE_MARCA
ON dw.FATO_ESTOQUE (SK_MARCA);

CREATE INDEX IDX_FE_FORNECEDOR
ON dw.FATO_ESTOQUE (SK_FORNECEDOR);

CREATE INDEX IDX_FE_DATA_REF
ON dw.FATO_ESTOQUE (DATA_REFERENCIA_ESTOQUE);

CREATE INDEX IDX_FE_PRODUTO_LOJA_TEMPO
ON dw.FATO_ESTOQUE (SK_PRODUTO, SK_LOJA, SK_TEMPO);


CREATE INDEX IDX_FE_LOJA_TEMPO
ON dw.FATO_ESTOQUE (SK_LOJA, SK_TEMPO);

CREATE INDEX IDX_FE_CATEGORIA_TEMPO
ON dw.FATO_ESTOQUE (SK_CATEGORIA, SK_TEMPO);

CREATE INDEX IDX_FE_MARCA_TEMPO
ON dw.FATO_ESTOQUE (SK_MARCA, SK_TEMPO);

CREATE INDEX IDX_FE_FORNECEDOR_TEMPO
ON dw.FATO_ESTOQUE (SK_FORNECEDOR, SK_TEMPO);

CREATE INDEX IDX_FE_FL_RUPTURA
ON dw.FATO_ESTOQUE (FL_RUPTURA);

CREATE INDEX IDX_FE_FL_ESTOQUE_BAIXO
ON dw.FATO_ESTOQUE (FL_ESTOQUE_BAIXO);

CREATE INDEX IDX_FE_FL_EXCESSO_ESTOQUE
ON dw.FATO_ESTOQUE (FL_EXCESSO_ESTOQUE);

CREATE INDEX IDX_FE_LOJA_PRODUTO_FLAGS
ON dw.FATO_ESTOQUE (
    SK_LOJA,
    SK_PRODUTO,
    FL_RUPTURA,
    FL_ESTOQUE_BAIXO,
    FL_EXCESSO_ESTOQUE
);

/* ============================================================
   ÍNDICES - dw.FATO_METAS
   Objetivo:
   Melhorar consultas de META vs REALIZADO / período,
   loja, canal, produto, categoria, marca e tipo de meta.
   ============================================================ */

CREATE INDEX IDX_FM_TEMPO
ON dw.FATO_METAS (SK_TEMPO);

CREATE INDEX IDX_FM_LOJA
ON dw.FATO_METAS (SK_LOJA);

CREATE INDEX IDX_FM_CANALVENDA
ON dw.FATO_METAS (SK_CANALVENDA);

CREATE INDEX IDX_FM_PRODUTO
ON dw.FATO_METAS (SK_PRODUTO);

CREATE INDEX IDX_FM_CATEGORIA
ON dw.FATO_METAS (SK_CATEGORIA);

CREATE INDEX IDX_FM_MARCA
ON dw.FATO_METAS (SK_MARCA);

CREATE INDEX IDX_FM_ANO_MES
ON dw.FATO_METAS (ANO_MES);

CREATE INDEX IDX_FM_TIPO_META
ON dw.FATO_METAS (TIPO_META);

CREATE INDEX IDX_FM_LOJA_CANAL_ANOMES
ON dw.FATO_METAS (SK_LOJA, SK_CANALVENDA, ANO_MES);

CREATE INDEX IDX_FM_CATEGORIA_ANOMES
ON dw.FATO_METAS (SK_CATEGORIA, ANO_MES);

CREATE INDEX IDX_FM_PRODUTO_ANOMES
ON dw.FATO_METAS (SK_PRODUTO, ANO_MES);

CREATE INDEX IDX_FM_MARCA_ANOMES
ON dw.FATO_METAS (SK_MARCA, ANO_MES);

CREATE INDEX IDX_FM_CONTEXTO_META
ON dw.FATO_METAS (
    ANO_MES,
    SK_LOJA,
    SK_CANALVENDA,
    SK_PRODUTO,
    SK_CATEGORIA,
    SK_MARCA,
    TIPO_META
);

CREATE INDEX IDX_FM_FL_META_ATIVA
ON dw.FATO_METAS (FL_META_ATIVA);

CREATE INDEX IDX_FM_PERIODO_META
ON dw.FATO_METAS (DATA_INICIO_META, DATA_FIM_META);

/* ============================================================
   ÍNDICES PARA DIMENSÕES
   ============================================================ */

CREATE INDEX IDX_DIM_PRODUTO_CATEGORIA
ON dw.DIM_PRODUTO (SK_CATEGORIA);

CREATE INDEX IDX_DIM_PRODUTO_MARCA
ON dw.DIM_PRODUTO (SK_MARCA);

CREATE INDEX IDX_DIM_PRODUTO_FORNECEDOR
ON dw.DIM_PRODUTO (SK_FORNECEDOR);

CREATE INDEX IDX_DIM_PRODUTO_ORIGEM
ON dw.DIM_PRODUTO (ID_PRODUTO_ORIGEM);

CREATE INDEX IDX_DIM_PRODUTO_ORIGEM_ATUAL
ON dw.DIM_PRODUTO (ID_PRODUTO_ORIGEM, FL_REGISTRO_ATUAL);

CREATE INDEX IDX_DIM_CLIENTE_ORIGEM
ON dw.DIM_CLIENTE (ID_CLIENTE_ORIGEM);

CREATE INDEX IDX_DIM_CLIENTE_ORIGEM_ATUAL
ON dw.DIM_CLIENTE (ID_CLIENTE_ORIGEM, FL_REGISTRO_ATUAL);

CREATE INDEX IDX_DIM_PROMOCAO_PERIODO
ON dw.DIM_PROMOCAO (DATA_INICIO_PROMOCAO, DATA_FIM_PROMOCAO);

CREATE INDEX IDX_DIM_SAZONALIDADE_PERIODO
ON dw.DIM_SAZONALIDADE (DATA_INICIO, DATA_FIM);

CREATE INDEX IDX_DIM_TEMPO_ANO_MES
ON dw.DIM_TEMPO (ANO_MES);

CREATE INDEX IDX_DIM_TEMPO_ANO_MES_DIA
ON dw.DIM_TEMPO (ANO, MES, DIA);

CREATE INDEX IDX_DIM_LOJA_REGIONAL
ON dw.DIM_LOJA (REGIONAL);

CREATE INDEX IDX_DIM_LOJA_UF
ON dw.DIM_LOJA (ESTADO);

CREATE INDEX IDX_DIM_CANALVENDA_TIPO
ON dw.DIM_CANALVENDA (TIPO_CANAL);

CREATE INDEX IDX_DIM_PRODUTORUPTURA_TIPO
ON dw.DIM_PRODUTORUPTURA (TIPO_RUPTURA);

/* ============================================================
   ÍNDICES DA TABELA dw.CONTROLE_CARGA
   ============================================================ */

   CREATE INDEX IDX_CC_PROCESSO_TABELA
ON dw.CONTROLE_CARGA (NOME_PROCESSO, NOME_TABELA);

CREATE INDEX IDX_CC_TABELA_STATUS
ON dw.CONTROLE_CARGA (NOME_TABELA, STATUS_CARGA);

CREATE INDEX IDX_CC_STATUS_CARGA
ON dw.CONTROLE_CARGA (STATUS_CARGA);

CREATE INDEX IDX_CC_TIPO_CARGA
ON dw.CONTROLE_CARGA (TIPO_CARGA);

CREATE INDEX IDX_CC_DATA_INICIO
ON dw.CONTROLE_CARGA (DATA_INICIO_CARGA);

CREATE INDEX IDX_CC_ULTIMA_DATA_PROC
ON dw.CONTROLE_CARGA (ULTIMA_DATA_PROCESSADA);

CREATE INDEX IDX_CC_ID_EXECUCAO
ON dw.CONTROLE_CARGA (ID_EXECUCAO);

/* ============================================================
   ÍNDICES DA TABELA dw.LOG_EXECUCAO
   ============================================================ */

   CREATE INDEX IDX_LOG_CONTROLE_CARGA
ON dw.LOG_EXECUCAO (ID_CONTROLE_CARGA);

CREATE INDEX IDX_LOG_ID_EXECUCAO
ON dw.LOG_EXECUCAO (ID_EXECUCAO);

CREATE INDEX IDX_LOG_PROCESSO
ON dw.LOG_EXECUCAO (NOME_PROCESSO);

CREATE INDEX IDX_LOG_PIPELINE
ON dw.LOG_EXECUCAO (NOME_PIPELINE);

CREATE INDEX IDX_LOG_ETAPA
ON dw.LOG_EXECUCAO (NOME_ETAPA);

CREATE INDEX IDX_LOG_TABELA
ON dw.LOG_EXECUCAO (NOME_TABELA);

CREATE INDEX IDX_LOG_STATUS_EVENTO
ON dw.LOG_EXECUCAO (STATUS_EVENTO);

CREATE INDEX IDX_LOG_TIPO_EVENTO
ON dw.LOG_EXECUCAO (TIPO_EVENTO);

CREATE INDEX IDX_LOG_DATA_LOG
ON dw.LOG_EXECUCAO (DATA_LOG);

CREATE INDEX IDX_LOG_PROCESSO_DATA
ON dw.LOG_EXECUCAO (NOME_PROCESSO, DATA_LOG);

CREATE INDEX IDX_LOG_EXECUCAO_STATUS
ON dw.LOG_EXECUCAO (ID_EXECUCAO, STATUS_EVENTO);