CREATE TABLE dw.FATO_VENDAS (
    SK_FATO_VENDA          NUMBER GENERATED ALWAYS AS IDENTITY,

    ID_VENDA_ORIGEM        VARCHAR2(50) NOT NULL,
    ID_ITEM_VENDA_ORIGEM   VARCHAR2(50),

    SK_TEMPO               NUMBER(8) NOT NULL,
    SK_CLIENTE             NUMBER,
    SK_PRODUTO             NUMBER NOT NULL,
    SK_CATEGORIA           NUMBER,
    SK_MARCA               NUMBER,
    SK_FORNECEDOR          NUMBER,
    SK_FORMAPAGTO          NUMBER,
    SK_PROMOCAO            NUMBER,
    SK_LOJA                NUMBER,
    SK_CANALVENDA          NUMBER,

    QUANTIDADE             NUMBER(18,4) DEFAULT 0 NOT NULL,
    VALOR_UNITARIO         NUMBER(18,2) DEFAULT 0 NOT NULL,
    VALOR_BRUTO            NUMBER(18,2) DEFAULT 0 NOT NULL,
    VALOR_DESCONTO         NUMBER(18,2) DEFAULT 0 NOT NULL,
    VALOR_LIQUIDO          NUMBER(18,2) DEFAULT 0 NOT NULL,
    CUSTO_TOTAL            NUMBER(18,2),
    MARGEM_BRUTA           NUMBER(18,2),

    DATA_HORA_VENDA        TIMESTAMP,
    DATA_CARGA             TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    DATA_ATUALIZACAO_DW    TIMESTAMP,

    CONSTRAINT PK_FATO_VENDAS PRIMARY KEY (SK_FATO_VENDA),

    CONSTRAINT FK_FV_TEMPO FOREIGN KEY (SK_TEMPO)
        REFERENCES dw.DIM_TEMPO (SK_TEMPO),

    CONSTRAINT FK_FV_CLIENTE FOREIGN KEY (SK_CLIENTE)
        REFERENCES dw.DIM_CLIENTE (SK_CLIENTE),

    CONSTRAINT FK_FV_PRODUTO FOREIGN KEY (SK_PRODUTO)
        REFERENCES dw.DIM_PRODUTO (SK_PRODUTO),

    CONSTRAINT FK_FV_CATEGORIA FOREIGN KEY (SK_CATEGORIA)
        REFERENCES dw.DIM_CATEGORIA (SK_CATEGORIA),

    CONSTRAINT FK_FV_MARCA FOREIGN KEY (SK_MARCA)
        REFERENCES dw.DIM_MARCA (SK_MARCA),

    CONSTRAINT FK_FV_FORNECEDOR FOREIGN KEY (SK_FORNECEDOR)
        REFERENCES dw.DIM_FORNECEDOR (SK_FORNECEDOR),

    CONSTRAINT FK_FV_FORMAPAGTO FOREIGN KEY (SK_FORMAPAGTO)
        REFERENCES dw.DIM_FORMAPAGTO (SK_FORMAPAGTO),

    CONSTRAINT FK_FV_PROMOCAO FOREIGN KEY (SK_PROMOCAO)
        REFERENCES dw.DIM_PROMOCAO (SK_PROMOCAO),

    CONSTRAINT FK_FV_LOJA FOREIGN KEY (SK_LOJA)
        REFERENCES dw.DIM_LOJA (SK_LOJA),

    CONSTRAINT FK_FV_CANALVENDA FOREIGN KEY (SK_CANALVENDA)
        REFERENCES dw.DIM_CANALVENDA (SK_CANALVENDA),

    CONSTRAINT CK_FV_QUANTIDADE CHECK (QUANTIDADE >= 0),
    CONSTRAINT CK_FV_VALOR_UNIT CHECK (VALOR_UNITARIO >= 0),
    CONSTRAINT CK_FV_VALOR_BRUTO CHECK (VALOR_BRUTO >= 0),
    CONSTRAINT CK_FV_VALOR_DESC CHECK (VALOR_DESCONTO >= 0),
    CONSTRAINT CK_FV_VALOR_LIQ CHECK (VALOR_LIQUIDO >= 0)
);

CREATE TABLE dw.FATO_RUPTURA_ESTOQUE (
    SK_FATO_RUPTURA        NUMBER GENERATED ALWAYS AS IDENTITY,

    ID_RUPTURA_ORIGEM      VARCHAR2(50),

    SK_TEMPO               NUMBER(8) NOT NULL,
    SK_PRODUTO             NUMBER NOT NULL,
    SK_LOJA                NUMBER NOT NULL,
    SK_PRODUTORUPTURA      NUMBER,

    QTD_ESTOQUE_ESPERADO   NUMBER(18,4),
    QTD_ESTOQUE_DISPONIVEL NUMBER(18,4),
    QTD_RUPTURA            NUMBER(18,4),
    DIAS_RUPTURA           NUMBER(10,2),
    VALOR_VENDA_PERDIDA    NUMBER(18,2),

    FL_RUPTURA             CHAR(1) DEFAULT 'S' NOT NULL,

    DATA_CARGA             TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    DATA_ATUALIZACAO_DW    TIMESTAMP,

    CONSTRAINT PK_FATO_RUPTURA PRIMARY KEY (SK_FATO_RUPTURA),

    CONSTRAINT FK_FR_TEMPO FOREIGN KEY (SK_TEMPO)
        REFERENCES dw.DIM_TEMPO (SK_TEMPO),

    CONSTRAINT FK_FR_PRODUTO FOREIGN KEY (SK_PRODUTO)
        REFERENCES dw.DIM_PRODUTO (SK_PRODUTO),

    CONSTRAINT FK_FR_LOJA FOREIGN KEY (SK_LOJA)
        REFERENCES dw.DIM_LOJA (SK_LOJA),

    CONSTRAINT FK_FR_MOTIVO FOREIGN KEY (SK_PRODUTORUPTURA)
        REFERENCES dw.DIM_PRODUTORUPTURA (SK_PRODUTORUPTURA),

    CONSTRAINT CK_FR_FL_RUPTURA CHECK (FL_RUPTURA IN ('S', 'N')),
    CONSTRAINT CK_FR_ESTOQUE_ESPERADO CHECK (
        QTD_ESTOQUE_ESPERADO IS NULL OR QTD_ESTOQUE_ESPERADO >= 0
    ),
    CONSTRAINT CK_FR_ESTOQUE_DISP CHECK (
        QTD_ESTOQUE_DISPONIVEL IS NULL OR QTD_ESTOQUE_DISPONIVEL >= 0
    ),
    CONSTRAINT CK_FR_QTD_RUPTURA CHECK (
        QTD_RUPTURA IS NULL OR QTD_RUPTURA >= 0
    ),
    CONSTRAINT CK_FR_VENDA_PERDIDA CHECK (
        VALOR_VENDA_PERDIDA IS NULL OR VALOR_VENDA_PERDIDA >= 0
    )
);

CREATE TABLE dw.FATO_ESTOQUE (
    SK_FATO_ESTOQUE            NUMBER GENERATED ALWAYS AS IDENTITY,

    ID_ESTOQUE_ORIGEM          VARCHAR2(50),

    SK_TEMPO                   NUMBER(8) NOT NULL,
    SK_PRODUTO                 NUMBER NOT NULL,
    SK_LOJA                    NUMBER NOT NULL,

    SK_CATEGORIA               NUMBER,
    SK_MARCA                   NUMBER,
    SK_FORNECEDOR              NUMBER,

    QTD_ESTOQUE_DISPONIVEL     NUMBER(18,4) DEFAULT 0 NOT NULL,
    QTD_ESTOQUE_RESERVADO      NUMBER(18,4) DEFAULT 0 NOT NULL,
    QTD_ESTOQUE_BLOQUEADO      NUMBER(18,4) DEFAULT 0 NOT NULL,
    QTD_ESTOQUE_TRANSITO       NUMBER(18,4) DEFAULT 0 NOT NULL,

    QTD_ESTOQUE_TOTAL          NUMBER(18,4) DEFAULT 0 NOT NULL,
    QTD_ESTOQUE_MINIMO         NUMBER(18,4),
    QTD_ESTOQUE_MAXIMO         NUMBER(18,4),
    QTD_PONTO_REPOSICAO        NUMBER(18,4),

    CUSTO_UNITARIO             NUMBER(18,2),
    VALOR_ESTOQUE_CUSTO        NUMBER(18,2),
    VALOR_ESTOQUE_VENDA        NUMBER(18,2),

    DIAS_COBERTURA_ESTOQUE     NUMBER(10,2),
    GIRO_ESTOQUE               NUMBER(10,4),

    FL_RUPTURA                 CHAR(1) DEFAULT 'N' NOT NULL,
    FL_ESTOQUE_BAIXO           CHAR(1) DEFAULT 'N' NOT NULL,
    FL_EXCESSO_ESTOQUE         CHAR(1) DEFAULT 'N' NOT NULL,

    DATA_REFERENCIA_ESTOQUE    DATE NOT NULL,
    DATA_CARGA                 TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    DATA_ATUALIZACAO_DW        TIMESTAMP,

    CONSTRAINT PK_FATO_ESTOQUE PRIMARY KEY (SK_FATO_ESTOQUE),

    CONSTRAINT FK_FE_TEMPO FOREIGN KEY (SK_TEMPO)
        REFERENCES dw.DIM_TEMPO (SK_TEMPO),

    CONSTRAINT FK_FE_PRODUTO FOREIGN KEY (SK_PRODUTO)
        REFERENCES dw.DIM_PRODUTO (SK_PRODUTO),

    CONSTRAINT FK_FE_LOJA FOREIGN KEY (SK_LOJA)
        REFERENCES dw.DIM_LOJA (SK_LOJA),

    CONSTRAINT FK_FE_CATEGORIA FOREIGN KEY (SK_CATEGORIA)
        REFERENCES dw.DIM_CATEGORIA (SK_CATEGORIA),

    CONSTRAINT FK_FE_MARCA FOREIGN KEY (SK_MARCA)
        REFERENCES dw.DIM_MARCA (SK_MARCA),

    CONSTRAINT FK_FE_FORNECEDOR FOREIGN KEY (SK_FORNECEDOR)
        REFERENCES dw.DIM_FORNECEDOR (SK_FORNECEDOR),

    CONSTRAINT CK_FE_QTD_DISP CHECK (QTD_ESTOQUE_DISPONIVEL >= 0),
    CONSTRAINT CK_FE_QTD_RES CHECK (QTD_ESTOQUE_RESERVADO >= 0),
    CONSTRAINT CK_FE_QTD_BLOQ CHECK (QTD_ESTOQUE_BLOQUEADO >= 0),
    CONSTRAINT CK_FE_QTD_TRANS CHECK (QTD_ESTOQUE_TRANSITO >= 0),
    CONSTRAINT CK_FE_QTD_TOTAL CHECK (QTD_ESTOQUE_TOTAL >= 0),

    CONSTRAINT CK_FE_QTD_MIN CHECK (
        QTD_ESTOQUE_MINIMO IS NULL OR QTD_ESTOQUE_MINIMO >= 0
    ),

    CONSTRAINT CK_FE_QTD_MAX CHECK (
        QTD_ESTOQUE_MAXIMO IS NULL OR QTD_ESTOQUE_MAXIMO >= 0
    ),

    CONSTRAINT CK_FE_PONTO_REPOSICAO CHECK (
        QTD_PONTO_REPOSICAO IS NULL OR QTD_PONTO_REPOSICAO >= 0
    ),

    CONSTRAINT CK_FE_CUSTO_UNIT CHECK (
        CUSTO_UNITARIO IS NULL OR CUSTO_UNITARIO >= 0
    ),

    CONSTRAINT CK_FE_VALOR_CUSTO CHECK (
        VALOR_ESTOQUE_CUSTO IS NULL OR VALOR_ESTOQUE_CUSTO >= 0
    ),

    CONSTRAINT CK_FE_VALOR_VENDA CHECK (
        VALOR_ESTOQUE_VENDA IS NULL OR VALOR_ESTOQUE_VENDA >= 0
    ),

    CONSTRAINT CK_FE_DIAS_COBERTURA CHECK (
        DIAS_COBERTURA_ESTOQUE IS NULL OR DIAS_COBERTURA_ESTOQUE >= 0
    ),

    CONSTRAINT CK_FE_GIRO CHECK (
        GIRO_ESTOQUE IS NULL OR GIRO_ESTOQUE >= 0
    ),

    CONSTRAINT CK_FE_FL_RUPTURA CHECK (FL_RUPTURA IN ('S', 'N')),
    CONSTRAINT CK_FE_FL_ESTOQUE_BAIXO CHECK (FL_ESTOQUE_BAIXO IN ('S', 'N')),
    CONSTRAINT CK_FE_FL_EXCESSO CHECK (FL_EXCESSO_ESTOQUE IN ('S', 'N'))

    CONSTRAINT UK_FE_PRODUTO_LOJA_TEMPO UNIQUE (SK_PRODUTO, SK_LOJA, SK_TEMPO)
);

CREATE TABLE dw.FATO_METAS (
    SK_FATO_META              NUMBER GENERATED ALWAYS AS IDENTITY,

    ID_META_ORIGEM            VARCHAR2(50),

    SK_TEMPO                  NUMBER(8) NOT NULL,
    SK_LOJA                   NUMBER,
    SK_CANALVENDA             NUMBER,
    SK_PRODUTO                NUMBER,
    SK_CATEGORIA              NUMBER,
    SK_MARCA                  NUMBER,

    ANO                       NUMBER(4) NOT NULL,
    MES                       NUMBER(2) NOT NULL,
    ANO_MES                   VARCHAR2(7) NOT NULL,

    TIPO_META                 VARCHAR2(100) NOT NULL,

    META_FATURAMENTO_BRUTO    NUMBER(18,2) DEFAULT 0 NOT NULL,
    META_FATURAMENTO_LIQUIDO  NUMBER(18,2) DEFAULT 0 NOT NULL,
    META_QTD_VENDAS           NUMBER(18,4) DEFAULT 0,
    META_QTD_ITENS            NUMBER(18,4) DEFAULT 0,
    META_TICKET_MEDIO         NUMBER(18,2),
    META_MARGEM_BRUTA         NUMBER(18,2),
    META_PERCENTUAL_MARGEM    NUMBER(9,4),

    DATA_INICIO_META          DATE NOT NULL,
    DATA_FIM_META             DATE NOT NULL,

    FL_META_ATIVA             CHAR(1) DEFAULT 'S' NOT NULL,
    DATA_CARGA                TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    DATA_ATUALIZACAO_DW       TIMESTAMP,

    CONSTRAINT PK_FATO_METAS PRIMARY KEY (SK_FATO_META),

    CONSTRAINT FK_FM_TEMPO FOREIGN KEY (SK_TEMPO)
        REFERENCES dw.DIM_TEMPO (SK_TEMPO),

    CONSTRAINT FK_FM_LOJA FOREIGN KEY (SK_LOJA)
        REFERENCES dw.DIM_LOJA (SK_LOJA),

    CONSTRAINT FK_FM_CANALVENDA FOREIGN KEY (SK_CANALVENDA)
        REFERENCES dw.DIM_CANALVENDA (SK_CANALVENDA),

    CONSTRAINT FK_FM_PRODUTO FOREIGN KEY (SK_PRODUTO)
        REFERENCES dw.DIM_PRODUTO (SK_PRODUTO),

    CONSTRAINT FK_FM_CATEGORIA FOREIGN KEY (SK_CATEGORIA)
        REFERENCES dw.DIM_CATEGORIA (SK_CATEGORIA),

    CONSTRAINT FK_FM_MARCA FOREIGN KEY (SK_MARCA)
        REFERENCES dw.DIM_MARCA (SK_MARCA),

    CONSTRAINT UK_FM_CONTEXTO_META UNIQUE (
        ANO_MES,
        SK_LOJA,
        SK_CANALVENDA,
        SK_PRODUTO,
        SK_CATEGORIA,
        SK_MARCA,
        TIPO_META
    ),

    CONSTRAINT CK_FM_MES CHECK (MES BETWEEN 1 AND 12),

    CONSTRAINT CK_FM_DATAS CHECK (
        DATA_FIM_META >= DATA_INICIO_META
    ),

    CONSTRAINT CK_FM_TIPO_META CHECK (
        TIPO_META IN (
            'FATURAMENTO',
            'VOLUME',
            'MARGEM',
            'TICKET_MEDIO',
            'MISTA'
        )
    ),

    CONSTRAINT CK_FM_FAT_BRUTO CHECK (
        META_FATURAMENTO_BRUTO >= 0
    ),

    CONSTRAINT CK_FM_FAT_LIQ CHECK (
        META_FATURAMENTO_LIQUIDO >= 0
    ),

    CONSTRAINT CK_FM_QTD_VENDAS CHECK (
        META_QTD_VENDAS IS NULL OR META_QTD_VENDAS >= 0
    ),

    CONSTRAINT CK_FM_QTD_ITENS CHECK (
        META_QTD_ITENS IS NULL OR META_QTD_ITENS >= 0
    ),

    CONSTRAINT CK_FM_TICKET_MEDIO CHECK (
        META_TICKET_MEDIO IS NULL OR META_TICKET_MEDIO >= 0
    ),

    CONSTRAINT CK_FM_MARGEM_BRUTA CHECK (
        META_MARGEM_BRUTA IS NULL OR META_MARGEM_BRUTA >= 0
    ),

    CONSTRAINT CK_FM_PERC_MARGEM CHECK (
        META_PERCENTUAL_MARGEM IS NULL 
        OR META_PERCENTUAL_MARGEM BETWEEN 0 AND 100
    ),

    CONSTRAINT CK_FM_ATIVA CHECK (
        FL_META_ATIVA IN ('S', 'N')
    )
);