CREATE TABLE dw.DIM_CATEGORIA (
    SK_CATEGORIA           NUMBER GENERATED ALWAYS AS IDENTITY,
    ID_CATEGORIA_ORIGEM    VARCHAR2(50) NOT NULL,
    NOME_CATEGORIA         VARCHAR2(150) NOT NULL,
    NOME_DEPARTAMENTO      VARCHAR2(150),
    FL_ATIVO               CHAR(1) DEFAULT 'S' NOT NULL,
    DATA_CARGA             TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    DATA_ATUALIZACAO_DW    TIMESTAMP,

    CONSTRAINT PK_DIM_CATEGORIA PRIMARY KEY (SK_CATEGORIA),
    CONSTRAINT UK_DIM_CATEGORIA_ORIGEM UNIQUE (ID_CATEGORIA_ORIGEM),
    CONSTRAINT CK_DIM_CATEGORIA_ATIVO CHECK (FL_ATIVO IN ('S', 'N'))
);

CREATE TABLE dw.DIM_MARCA (
    SK_MARCA               NUMBER GENERATED ALWAYS AS IDENTITY,
    ID_MARCA_ORIGEM        VARCHAR2(50) NOT NULL,
    NOME_MARCA             VARCHAR2(150) NOT NULL,
    PAIS_ORIGEM            VARCHAR2(100),
    FL_MARCA_PROPRIA       CHAR(1) DEFAULT 'N' NOT NULL,
    FL_ATIVO               CHAR(1) DEFAULT 'S' NOT NULL,
    DATA_CARGA             TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    DATA_ATUALIZACAO_DW    TIMESTAMP,

    CONSTRAINT PK_DIM_MARCA PRIMARY KEY (SK_MARCA),
    CONSTRAINT UK_DIM_MARCA_ORIGEM UNIQUE (ID_MARCA_ORIGEM),
    CONSTRAINT CK_DIM_MARCA_PROPRIA CHECK (FL_MARCA_PROPRIA IN ('S', 'N')),
    CONSTRAINT CK_DIM_MARCA_ATIVO CHECK (FL_ATIVO IN ('S', 'N'))
);

CREATE TABLE dw.DIM_FORNECEDOR (
    SK_FORNECEDOR          NUMBER GENERATED ALWAYS AS IDENTITY,
    ID_FORNECEDOR_ORIGEM   VARCHAR2(50) NOT NULL,
    NOME_FORNECEDOR        VARCHAR2(200) NOT NULL,
    CNPJ_FORNECEDOR        VARCHAR2(20),
    CIDADE                 VARCHAR2(100),
    ESTADO                 VARCHAR2(2),
    PAIS                   VARCHAR2(100) DEFAULT 'Brasil',
    TIPO_FORNECEDOR        VARCHAR2(100),
    FL_ATIVO               CHAR(1) DEFAULT 'S' NOT NULL,
    DATA_CARGA             TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    DATA_ATUALIZACAO_DW    TIMESTAMP,

    CONSTRAINT PK_DIM_FORNECEDOR PRIMARY KEY (SK_FORNECEDOR),
    CONSTRAINT UK_DIM_FORNECEDOR_ORIGEM UNIQUE (ID_FORNECEDOR_ORIGEM),
    CONSTRAINT CK_DIM_FORNECEDOR_ATIVO CHECK (FL_ATIVO IN ('S', 'N'))
);

CREATE TABLE dw.DIM_PRODUTO (
    SK_PRODUTO             NUMBER GENERATED ALWAYS AS IDENTITY,
    ID_PRODUTO_ORIGEM      VARCHAR2(50) NOT NULL,

    SK_CATEGORIA           NUMBER NOT NULL,
    SK_MARCA               NUMBER,
    SK_FORNECEDOR          NUMBER,

    NOME_PRODUTO           VARCHAR2(250) NOT NULL,
    DESCRICAO_PRODUTO      VARCHAR2(500),
    CODIGO_BARRAS          VARCHAR2(50),
    SKU                    VARCHAR2(100),

    UNIDADE_MEDIDA         VARCHAR2(20),
    PESO_KG                NUMBER(18,4),
    ALTURA_CM              NUMBER(18,4),
    LARGURA_CM             NUMBER(18,4),
    PROFUNDIDADE_CM        NUMBER(18,4),

    CUSTO_UNITARIO         NUMBER(18,2),
    PRECO_LISTA            NUMBER(18,2),

    FL_PERECIVEL           CHAR(1) DEFAULT 'N' NOT NULL,
    FL_ATIVO               CHAR(1) DEFAULT 'S' NOT NULL,

    DATA_INICIO_VIGENCIA   DATE DEFAULT SYSDATE NOT NULL,
    DATA_FIM_VIGENCIA      DATE,
    FL_REGISTRO_ATUAL      CHAR(1) DEFAULT 'S' NOT NULL,

    DATA_CARGA             TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    DATA_ATUALIZACAO_DW    TIMESTAMP,

    CONSTRAINT PK_DIM_PRODUTO PRIMARY KEY (SK_PRODUTO),
    CONSTRAINT FK_PRODUTO_CATEGORIA FOREIGN KEY (SK_CATEGORIA)
        REFERENCES dw.DIM_CATEGORIA (SK_CATEGORIA),
    CONSTRAINT FK_PRODUTO_MARCA FOREIGN KEY (SK_MARCA)
        REFERENCES dw.DIM_MARCA (SK_MARCA),
    CONSTRAINT FK_PRODUTO_FORNECEDOR FOREIGN KEY (SK_FORNECEDOR)
        REFERENCES dw.DIM_FORNECEDOR (SK_FORNECEDOR),
    CONSTRAINT CK_DIM_PRODUTO_PERECIVEL CHECK (FL_PERECIVEL IN ('S', 'N')),
    CONSTRAINT CK_DIM_PRODUTO_ATIVO CHECK (FL_ATIVO IN ('S', 'N')),
    CONSTRAINT CK_DIM_PRODUTO_ATUAL CHECK (FL_REGISTRO_ATUAL IN ('S', 'N')),
    CONSTRAINT CK_DIM_PRODUTO_CUSTO CHECK (CUSTO_UNITARIO IS NULL OR CUSTO_UNITARIO >= 0),
    CONSTRAINT CK_DIM_PRODUTO_PRECO CHECK (PRECO_LISTA IS NULL OR PRECO_LISTA >= 0)
);

CREATE TABLE dw.DIM_CLIENTE (
    SK_CLIENTE             NUMBER GENERATED ALWAYS AS IDENTITY,
    ID_CLIENTE_ORIGEM      VARCHAR2(50) NOT NULL,

    NOME_CLIENTE           VARCHAR2(200),
    TIPO_CLIENTE           VARCHAR2(50),
    CPF_CNPJ               VARCHAR2(20),
    SEXO                   VARCHAR2(20),
    FAIXA_ETARIA           VARCHAR2(50),
    DATA_NASCIMENTO        DATE,

    CIDADE                 VARCHAR2(100),
    ESTADO                 VARCHAR2(2),
    PAIS                   VARCHAR2(100) DEFAULT 'Brasil',
    SEGMENTO_CLIENTE       VARCHAR2(100),

    DATA_CADASTRO          DATE,

    DATA_INICIO_VIGENCIA   DATE DEFAULT SYSDATE NOT NULL,
    DATA_FIM_VIGENCIA      DATE,
    FL_REGISTRO_ATUAL      CHAR(1) DEFAULT 'S' NOT NULL,
    FL_ATIVO               CHAR(1) DEFAULT 'S' NOT NULL,

    DATA_CARGA             TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    DATA_ATUALIZACAO_DW    TIMESTAMP,

    CONSTRAINT PK_DIM_CLIENTE PRIMARY KEY (SK_CLIENTE),
    CONSTRAINT CK_DIM_CLIENTE_ATUAL CHECK (FL_REGISTRO_ATUAL IN ('S', 'N')),
    CONSTRAINT CK_DIM_CLIENTE_ATIVO CHECK (FL_ATIVO IN ('S', 'N')),
    CONSTRAINT CK_DIM_CLIENTE_TIPO CHECK (TIPO_CLIENTE IN ('PF', 'PJ') OR TIPO_CLIENTE IS NULL),
    CONSTRAINT CK_DIM_CLIENTE_VIGENCIA CHECK (
        DATA_FIM_VIGENCIA IS NULL OR DATA_FIM_VIGENCIA >= DATA_INICIO_VIGENCIA
    )
);

CREATE TABLE dw.DIM_FORMAPAGTO (
    SK_FORMAPAGTO          NUMBER GENERATED ALWAYS AS IDENTITY,
    ID_FORMAPAGTO_ORIGEM   VARCHAR2(50) NOT NULL,

    DESCRICAO_FORMAPAGTO   VARCHAR2(100) NOT NULL,
    TIPO_FORMAPAGTO        VARCHAR2(50),
    MODALIDADE             VARCHAR2(50),
    QTD_PARCELAS           NUMBER(3),

    FL_CREDITO             CHAR(1) DEFAULT 'N' NOT NULL,
    FL_ATIVO               CHAR(1) DEFAULT 'S' NOT NULL,

    DATA_CARGA             TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    DATA_ATUALIZACAO_DW    TIMESTAMP,

    CONSTRAINT PK_DIM_FORMAPAGTO PRIMARY KEY (SK_FORMAPAGTO),
    CONSTRAINT UK_DIM_FORMAPAGTO_ORIGEM UNIQUE (ID_FORMAPAGTO_ORIGEM),
    CONSTRAINT CK_DIM_FORMAPAGTO_CREDITO CHECK (FL_CREDITO IN ('S', 'N')),
    CONSTRAINT CK_DIM_FORMAPAGTO_ATIVO CHECK (FL_ATIVO IN ('S', 'N')),
    CONSTRAINT CK_DIM_FORMAPAGTO_PARCELAS CHECK (QTD_PARCELAS IS NULL OR QTD_PARCELAS >= 0)
);

CREATE TABLE dw.DIM_PROMOCAO (
    SK_PROMOCAO            NUMBER GENERATED ALWAYS AS IDENTITY,
    ID_PROMOCAO_ORIGEM     VARCHAR2(50) NOT NULL,

    NOME_PROMOCAO          VARCHAR2(200) NOT NULL,
    TIPO_PROMOCAO          VARCHAR2(100),
    MECANICA_PROMOCAO      VARCHAR2(200),

    DATA_INICIO_PROMOCAO   DATE NOT NULL,
    DATA_FIM_PROMOCAO      DATE NOT NULL,

    PERCENTUAL_DESCONTO    NUMBER(9,4),
    VALOR_DESCONTO         NUMBER(18,2),
    FL_PROMOCAO_ATIVA      CHAR(1) DEFAULT 'S' NOT NULL,

    DATA_CARGA             TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    DATA_ATUALIZACAO_DW    TIMESTAMP,

    CONSTRAINT PK_DIM_PROMOCAO PRIMARY KEY (SK_PROMOCAO),
    CONSTRAINT UK_DIM_PROMOCAO_ORIGEM UNIQUE (ID_PROMOCAO_ORIGEM),
    CONSTRAINT CK_DIM_PROMOCAO_DATAS CHECK (DATA_FIM_PROMOCAO >= DATA_INICIO_PROMOCAO),
    CONSTRAINT CK_DIM_PROMOCAO_ATIVA CHECK (FL_PROMOCAO_ATIVA IN ('S', 'N')),
    CONSTRAINT CK_DIM_PROMOCAO_PERC CHECK (
        PERCENTUAL_DESCONTO IS NULL OR PERCENTUAL_DESCONTO BETWEEN 0 AND 100
    ),
    CONSTRAINT CK_DIM_PROMOCAO_VALOR CHECK (
        VALOR_DESCONTO IS NULL OR VALOR_DESCONTO >= 0
    )
);

CREATE TABLE dw.DIM_SAZONALIDADE (
    SK_SAZONALIDADE        NUMBER GENERATED ALWAYS AS IDENTITY,
    ID_SAZONALIDADE_ORIGEM VARCHAR2(50) NOT NULL,

    NOME_SAZONALIDADE      VARCHAR2(150) NOT NULL,
    TIPO_SAZONALIDADE      VARCHAR2(100),
    DESCRICAO              VARCHAR2(500),

    DATA_INICIO            DATE NOT NULL,
    DATA_FIM               DATE NOT NULL,

    FL_RECORRENTE          CHAR(1) DEFAULT 'S' NOT NULL,
    FL_ATIVO               CHAR(1) DEFAULT 'S' NOT NULL,

    DATA_CARGA             TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    DATA_ATUALIZACAO_DW    TIMESTAMP,

    CONSTRAINT PK_DIM_SAZONALIDADE PRIMARY KEY (SK_SAZONALIDADE),
    CONSTRAINT UK_DIM_SAZONALIDADE_ORIGEM UNIQUE (ID_SAZONALIDADE_ORIGEM),
    CONSTRAINT CK_DIM_SAZONALIDADE_DATAS CHECK (DATA_FIM >= DATA_INICIO),
    CONSTRAINT CK_DIM_SAZONALIDADE_RECOR CHECK (FL_RECORRENTE IN ('S', 'N')),
    CONSTRAINT CK_DIM_SAZONALIDADE_ATIVO CHECK (FL_ATIVO IN ('S', 'N'))
);

CREATE TABLE dw.DIM_TEMPO (
    SK_TEMPO               NUMBER(8) NOT NULL,
    DATA_COMPLETA          DATE NOT NULL,

    DIA                    NUMBER(2) NOT NULL,
    MES                    NUMBER(2) NOT NULL,
    ANO                    NUMBER(4) NOT NULL,

    NOME_DIA_SEMANA        VARCHAR2(30),
    NUM_DIA_SEMANA         NUMBER(1),
    NOME_MES               VARCHAR2(30),
    ANO_MES                VARCHAR2(7),
    TRIMESTRE              NUMBER(1),
    SEMESTRE               NUMBER(1),

    FL_FIM_SEMANA          CHAR(1) DEFAULT 'N' NOT NULL,
    FL_FERIADO             CHAR(1) DEFAULT 'N' NOT NULL,
    NOME_FERIADO           VARCHAR2(150),

    DATA_CARGA             TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,

    CONSTRAINT PK_DIM_TEMPO PRIMARY KEY (SK_TEMPO),
    CONSTRAINT UK_DIM_TEMPO_DATA UNIQUE (DATA_COMPLETA),
    CONSTRAINT CK_DIM_TEMPO_MES CHECK (MES BETWEEN 1 AND 12),
    CONSTRAINT CK_DIM_TEMPO_DIA CHECK (DIA BETWEEN 1 AND 31),
    CONSTRAINT CK_DIM_TEMPO_TRIM CHECK (TRIMESTRE BETWEEN 1 AND 4),
    CONSTRAINT CK_DIM_TEMPO_SEM CHECK (SEMESTRE BETWEEN 1 AND 2),
    CONSTRAINT CK_DIM_TEMPO_FIMSEMANA CHECK (FL_FIM_SEMANA IN ('S', 'N')),
    CONSTRAINT CK_DIM_TEMPO_FERIADO CHECK (FL_FERIADO IN ('S', 'N'))
);

CREATE TABLE dw.DIM_PRODUTORUPTURA (
    SK_PRODUTORUPTURA      NUMBER GENERATED ALWAYS AS IDENTITY,
    ID_RUPTURA_ORIGEM      VARCHAR2(50) NOT NULL,

    DESCRICAO_RUPTURA      VARCHAR2(200) NOT NULL,
    TIPO_RUPTURA           VARCHAR2(100),
    RESPONSAVEL_RUPTURA    VARCHAR2(100),

    FL_ATIVO               CHAR(1) DEFAULT 'S' NOT NULL,
    DATA_CARGA             TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    DATA_ATUALIZACAO_DW    TIMESTAMP,

    CONSTRAINT PK_DIM_PRODUTORUPTURA PRIMARY KEY (SK_PRODUTORUPTURA),
    CONSTRAINT UK_DIM_PRODUTORUPTURA_ORIGEM UNIQUE (ID_RUPTURA_ORIGEM),
    CONSTRAINT CK_DIM_PRODUTORUPTURA_ATIVO CHECK (FL_ATIVO IN ('S', 'N'))
);

CREATE TABLE dw.DIM_LOJA (
    SK_LOJA                NUMBER GENERATED ALWAYS AS IDENTITY,
    ID_LOJA_ORIGEM         VARCHAR2(50) NOT NULL,

    NOME_LOJA              VARCHAR2(200) NOT NULL,
    CNPJ_LOJA              VARCHAR2(20),
    TIPO_LOJA              VARCHAR2(100),

    CIDADE                 VARCHAR2(100),
    ESTADO                 VARCHAR2(2),
    REGIONAL               VARCHAR2(100),
    PAIS                   VARCHAR2(100) DEFAULT 'Brasil',

    DATA_ABERTURA          DATE,
    FL_ATIVO               CHAR(1) DEFAULT 'S' NOT NULL,

    DATA_CARGA             TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    DATA_ATUALIZACAO_DW    TIMESTAMP,

    CONSTRAINT PK_DIM_LOJA PRIMARY KEY (SK_LOJA),
    CONSTRAINT UK_DIM_LOJA_ORIGEM UNIQUE (ID_LOJA_ORIGEM),
    CONSTRAINT CK_DIM_LOJA_ATIVO CHECK (FL_ATIVO IN ('S', 'N'))
);

CREATE TABLE dw.DIM_CANALVENDA (
    SK_CANALVENDA          NUMBER GENERATED ALWAYS AS IDENTITY,
    ID_CANALVENDA_ORIGEM   VARCHAR2(50) NOT NULL,

    NOME_CANALVENDA        VARCHAR2(100) NOT NULL,
    TIPO_CANAL             VARCHAR2(100),
    DESCRICAO_CANAL        VARCHAR2(300),

    FL_ATIVO               CHAR(1) DEFAULT 'S' NOT NULL,
    DATA_CARGA             TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    DATA_ATUALIZACAO_DW    TIMESTAMP,

    CONSTRAINT PK_DIM_CANALVENDA PRIMARY KEY (SK_CANALVENDA),
    CONSTRAINT UK_DIM_CANALVENDA_ORIGEM UNIQUE (ID_CANALVENDA_ORIGEM),
    CONSTRAINT CK_DIM_CANALVENDA_ATIVO CHECK (FL_ATIVO IN ('S', 'N'))
);

ALTER TABLE dw.DIM_PRODUTO ADD CONSTRAINT CK_DIM_PRODUTO_PESO
CHECK (PESO_KG IS NULL OR PESO_KG >= 0);

ALTER TABLE dw.DIM_PRODUTO ADD CONSTRAINT CK_DIM_PRODUTO_ALTURA
CHECK (ALTURA_CM IS NULL OR ALTURA_CM >= 0);

ALTER TABLE dw.DIM_PRODUTO ADD CONSTRAINT CK_DIM_PRODUTO_LARGURA
CHECK (LARGURA_CM IS NULL OR LARGURA_CM >= 0);

ALTER TABLE dw.DIM_PRODUTO ADD CONSTRAINT CK_DIM_PRODUTO_PROFUNDIDADE
CHECK (PROFUNDIDADE_CM IS NULL OR PROFUNDIDADE_CM >= 0);

ALTER TABLE dw.DIM_PRODUTO ADD CONSTRAINT CK_DIM_PRODUTO_VIGENCIA
CHECK (
    DATA_FIM_VIGENCIA IS NULL 
    OR DATA_FIM_VIGENCIA >= DATA_INICIO_VIGENCIA
);

ALTER TABLE dw.DIM_TEMPO ADD CONSTRAINT CK_DIM_TEMPO_DIA_SEMANA
CHECK (NUM_DIA_SEMANA BETWEEN 1 AND 7);

ALTER TABLE dw.DIM_FORNECEDOR ADD CONSTRAINT CK_DIM_FORNECEDOR_ESTADO
CHECK (ESTADO IS NULL OR LENGTH(ESTADO) = 2);

ALTER TABLE dw.DIM_LOJA ADD CONSTRAINT CK_DIM_LOJA_ESTADO
CHECK (ESTADO IS NULL OR LENGTH(ESTADO) = 2);