-- Consultas exemplo para consumo de BI na camada Gold

-- 1. Faturamento mensal executivo
SELECT
    ANO_MES,
    FATURAMENTO_LIQUIDO,
    MARGEM_BRUTA,
    PERCENTUAL_MARGEM,
    QTD_VENDAS,
    TICKET_MEDIO,
    PERCENTUAL_ATINGIMENTO_META,
    VALOR_VENDA_PERDIDA
FROM gold.mart_resumo_executivo
ORDER BY ANO_MES;

-- 2. Top categorias por faturamento
SELECT
    ANO_MES,
    NOME_CATEGORIA,
    SUM(FATURAMENTO_LIQUIDO) AS FATURAMENTO_LIQUIDO,
    SUM(MARGEM_BRUTA) AS MARGEM_BRUTA,
    SUM(QTD_ITENS) AS QTD_ITENS
FROM gold.kpi_vendas_mensal
GROUP BY ANO_MES, NOME_CATEGORIA
ORDER BY ANO_MES, FATURAMENTO_LIQUIDO DESC;

-- 3. Meta versus realizado por loja
SELECT
    ANO_MES,
    NOME_LOJA,
    REGIONAL,
    SUM(META_FATURAMENTO_LIQUIDO) AS META_FATURAMENTO_LIQUIDO,
    SUM(FATURAMENTO_LIQUIDO_REALIZADO) AS FATURAMENTO_LIQUIDO_REALIZADO,
    ROUND(SUM(FATURAMENTO_LIQUIDO_REALIZADO) / NULLIF(SUM(META_FATURAMENTO_LIQUIDO), 0) * 100, 2) AS PERCENTUAL_ATINGIMENTO
FROM gold.kpi_meta_vs_realizado
GROUP BY ANO_MES, NOME_LOJA, REGIONAL
ORDER BY ANO_MES, PERCENTUAL_ATINGIMENTO DESC;

-- 4. Produtos em ruptura ou estoque baixo
SELECT
    DATA_REFERENCIA,
    NOME_LOJA,
    NOME_PRODUTO,
    NOME_CATEGORIA,
    QTD_ESTOQUE_DISPONIVEL,
    QTD_PONTO_REPOSICAO,
    STATUS_ESTOQUE,
    VALOR_ESTOQUE_CUSTO
FROM gold.kpi_estoque_atual
WHERE STATUS_ESTOQUE IN ('RUPTURA', 'ESTOQUE_BAIXO')
ORDER BY STATUS_ESTOQUE, NOME_LOJA, NOME_PRODUTO;

-- 5. Venda perdida por motivo de ruptura
SELECT
    ANO_MES,
    TIPO_RUPTURA,
    DESCRICAO_RUPTURA,
    SUM(QTD_EVENTOS_RUPTURA) AS QTD_EVENTOS_RUPTURA,
    SUM(VALOR_VENDA_PERDIDA) AS VALOR_VENDA_PERDIDA
FROM gold.kpi_ruptura_mensal
GROUP BY ANO_MES, TIPO_RUPTURA, DESCRICAO_RUPTURA
ORDER BY ANO_MES, VALOR_VENDA_PERDIDA DESC;
